RT2237A3/Controllers/MediaTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RT2237A3.Controllers
{
    public class MediaTypesController : Controller
    {
        Manager m = new Manager();
        // GET: MediaTypes
        public ActionResult Index()
        {
            var mediaTypes = m.MediaTypeGetAll();
            return View(mediaTypes);
        }
    }
}

RT2237A3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title - RT2237A3</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Playlist Editor" />
    <meta name="application-name" content="2237-e943f9f1-bf57-40da-b2ba-8ebfe46db6bf" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Playlist Editor", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Albums", "Index", "Albums", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Artists", "Index", "Artists", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Media Types", "Index", "MediaTypes", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Tracks", "Index", "Tracks", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Playlists", "Index", "Playlists", new { area = "" }, new { @class = "nav-link" })</li>
                    @*<li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                <small>
                    By submitting this assignment you agree to the following:
                    I declare that this assignment is my own work in accordance with the Seneca Academic
                    Policy. No part of this assignment has been copied manually or electronically from
                    any other source (including web sites) or distributed to other students.
                </small>
            </p>
            <p>&copy; Rohan Tankala, rtankala1@myseneca.ca, WEB524, Fall 2023</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>