RT2237A3/Controllers/PlaylistsController.cs
using RT2237A3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;


namespace RT2237A3.Controllers
{
    public class PlaylistsController : Controller
    {
        Manager m = new Manager();
        // GET: Playlists
        public ActionResult Index()
        {
            var playlists = m.PlaylistGetAll();
            return View(playlists);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var playlist = m.PlaylistGetById(id.Value);

            if (playlist == null)
            {
                return HttpNotFound();
            }

            return View(playlist);
        }

        public ActionResult Edit(int id)
        {
            var playlist = m.PlaylistGetById(id);
            if (playlist == null)
            {
                return HttpNotFound();
            }

            var selectedTrackIds = playlist.Tracks.Select(t => t.TrackId).ToList();

            var allTracks = m.TrackGetAll();
            var trackSelectionsList = new MultiSelectList(allTracks, "TrackId", "NameFull", selectedTrackIds);

            var formModel = new PlaylistEditTracksFormViewModel
            {
                Id = playlist.PlaylistId,
                Name = playlist.Name,
                Tracks = playlist.Tracks,
                CurrentTracks = playlist.Tracks.Select(t => new TrackBaseViewModel
                {
                    TrackId = t.TrackId,
                    Name = t.NameShort,
                    Composer = t.Composer,
                    Milliseconds = t.Milliseconds,
                    UnitPrice = t.UnitPrice
                }),
                TrackSelectionsList = trackSelectionsList
            };

            return View(formModel);
        }

        [HttpPost]
        public ActionResult Edit(PlaylistEditTracksViewModel model)
        {
            if (model.SelectedTrackIds == null)
            {
                model.SelectedTrackIds = new int[0];
            }

            if (ModelState.IsValid)
            {
                m.UpdatePlaylistTracks(model.Id, model.SelectedTrackIds);
                return RedirectToAction("Details", new { id = model.Id });
            }

            return View(model);
        }



    }
}

RT2237A3/Views/Playlists/Details.cshtml
@model RT2237A3.Models.PlaylistBaseViewModel

@{
    ViewBag.Title = "Playlist details - " + Model.Name;
}

<h2>Playlist details - <span class="bg-info">@Model.Name</span></h2>
<hr />
@Html.ActionLink("Edit", "Edit", new { id = Model.PlaylistId }) |
@Html.ActionLink("Back to List", "Index")
<hr />
<h4>Playlist Name: <span class="bg-info">@Model.Name</span></h4>

<h5>Tracks on the Playlist <span class="badge bg-primary">@Model.TracksCount</span></h5>
<ul>
    @foreach (var track in Model.Tracks)
    {
    <li>@track.Name</li>
    }
</ul>
@Html.ActionLink("Edit", "Edit", new { id = Model.PlaylistId }) |
@Html.ActionLink("Back to List", "Index")

RT2237A3/Views/Playlists/Edit.cshtml
@model RT2237A3.Models.PlaylistEditTracksFormViewModel

@{
    ViewBag.Title = "Playlist details - " + Model.Name;
}

<h1>Playlist details - @Model.Name</h1>

@using (Html.BeginForm("Edit", "Playlists", FormMethod.Post))
{
<div>
    <input type="submit" value="Save changes" style="margin-left: 10px;" />
    |    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Back to Details", "Details", new { id = Model.Id })
</div>

<div class="row">
    <div class="col-md-6">
        <table>
            @foreach (var item in Model.TrackSelectionsList)
            {
            <tr>
                <td>
                    <input type="checkbox" name="SelectedTrackIds" value="@item.Value" checked="@item.Selected" />
                    @item.Text
                </td>
            </tr>
            }
        </table>
    </div>
    <div class="col-md-6 card">
        <h4>Now on Playlist</h4>
        @foreach (var track in Model.CurrentTracks)
        {
        <div>
            @track.Name
        </div>
        }
    </div>
</div>

<div>
    <input type="submit" value="Save changes" style="margin-left: 10px;" />
    |    @Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Back to Details", "Details", new { id = Model.Id })
</div>
}

RT2237A3/Views/Playlists/Index.cshtml
@model IEnumerable<RT2237A3.Models.PlaylistBaseViewModel>

    @{
    ViewBag.Title = "Index";
    }

    <h2>List of Playlists</h2>

    @*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
    <table class="table">
        <thead>
            <tr>

                <th>@Html.DisplayNameFor(model => model.Name)</th>
                <th>@Html.DisplayNameFor(model => model.TracksCount)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var playlist in Model)
            {
            <tr>
                <td>@playlist.Name</td>
                <td><span class="badge bg-primary">@playlist.TracksCount</span></td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=playlist.PlaylistId }) |
                    @Html.ActionLink("Details", "Details", new { id = playlist.PlaylistId })
                </td>
            </tr>
            }
        </tbody>
    </table>